module.exports = {
  Badge: require("./components/Badge"),
  Bubble: require("./components/Bubble"),
  Button: require("./components/Button"),
  Card: require("./components/Card"),
  Carousel: require("./components/Carousel"),
  Checkbox: require("./components/Checkbox"),
  Gravatar: require("./components/Gravatar"),
  Icon: require("./components/Icon"),
  Indicator: require("./components/Indicator"),
  Input: require("./components/Input"),
  Progress: require("./components/Progress"),
  Radio: require("./components/Radio"),
  RadioGroup: require("./components/RadioGroup"),
  SegmentedControlButton: require("./components/SegmentedControlButton"),
  Slider: require("./components/Slider"),
  Spinner: require("./components/Spinner"),
  Switcher: require("./components/Switcher"),
  WebStyles: require("./components/WebStyles"),

  // NOTE: Typography
  A: require("./components/typography/A"),
  B: require("./components/typography/B"),
  Em: require("./components/typography/Em"),
  H1: require("./components/typography/H1"),
  H2: require("./components/typography/H2"),
  H3: require("./components/typography/H3"),
  H4: require("./components/typography/H4"),
  H5: require("./components/typography/H5"),
  H6: require("./components/typography/H6"),
  I: require("./components/typography/I"),
  P: require("./components/typography/P"),
  Strong: require("./components/typography/Strong"),
  // theme
  withTheme: require("./components/Theme").withTheme,
  ThemeProvider: require("./components/Theme").Provider
};
