module.exports = {
  Badge: require("./Badge"),
  Bubble: require("./Bubble"),
  Button: require("./Button"),
  Card: require("./Card"),
  Carousel: require("./Carousel"),
  Checkbox: require("./Checkbox"),
  Gravatar: require("./Gravatar"),
  Indicator: require("./Indicator"),
  Input: require("./Input"),
  Progress: require("./Progress"),
  Radio: require("./Radio"),
  RadioGroup: require("./RadioGroup"),
  SegmentedControlButton: require("./SegmentedControlButton"),
  Slider: require("./Slider"),
  Spinner: require("./Spinner"),
  Switcher: require("./Switcher"),

  // NOTE: Typography
  A: require("./typography/A"),
  B: require("./typography/B"),
  Em: require("./typography/Em"),
  H1: require("./typography/H1"),
  H2: require("./typography/H2"),
  H3: require("./typography/H3"),
  H4: require("./typography/H4"),
  H5: require("./typography/H5"),
  H6: require("./typography/H6"),
  I: require("./typography/I"),
  P: require("./typography/P"),
  Strong: require("./typography/Strong"),
  // theme
  withTheme: require("./Theme").withTheme,
  ThemeProvider: require("./Theme").Provider
};
